# Generated by Django 3.2.4 on 2021-06-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dietorder',
            name='address_info',
        ),
        migrations.RemoveField(
            model_name='dietorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dietorder',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='dietorder',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='dietorder',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='dietorder',
            name='state',
        ),
    ]
