# Generated by Django 3.2.4 on 2021-06-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietorder',
            name='delivery_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='delivery_cost_per_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='diet_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='diet_cost_per_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dietorder',
            name='to_pay',
            field=models.FloatField(null=True),
        ),
    ]
