# Generated by Django 3.2.4 on 2021-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietorder',
            name='is_not_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
