# Generated by Django 3.2.4 on 2021-06-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietorder',
            old_name='day_of_end',
            new_name='date_of_end',
        ),
    ]
