# Generated by Django 3.2.4 on 2021-06-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_auto_20210624_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietorder',
            name='date_of_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dietorder',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dietorder',
            name='diet_cost_per_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dietorder',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PurchaserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('address_info', models.TextField()),
                ('locality', models.TextField()),
                ('state', models.TextField()),
                ('post_code', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
