# Generated by Django 3.2.4 on 2021-06-28 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0003_auto_20210628_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserinfo',
            name='post_code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='OrderConfirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('payment_method', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
