# Generated by Django 3.2.4 on 2021-06-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210620_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietorder',
            name='country',
        ),
    ]
