# Generated by Django 3.2.4 on 2021-06-22 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_dietorder_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietorder',
            name='date_of_start',
            field=models.DateTimeField(default=datetime.date(2021, 6, 22)),
        ),
    ]
