# Generated by Django 3.2.4 on 2021-06-28 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210628_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmed',
            name='date_of_purchase',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
