# Generated by Django 3.2.4 on 2021-07-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210704_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='note',
            field=models.TextField(default='elo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='address_info',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='locality',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='post_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='ordercheckout',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
