# Generated by Django 3.2.4 on 2021-06-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_orderconfirmed_date_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietorder',
            name='confirmed_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.orderconfirmed'),
        ),
        migrations.AddField(
            model_name='orderconfirmed',
            name='to_pay',
            field=models.FloatField(null=True),
        ),
    ]
