# Generated by Django 3.2.4 on 2021-07-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('checkout', '0006_auto_20210704_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordercheckout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaserinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='dietorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercheckout',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserinfo',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.customer'),
            preserve_default=False,
        ),
    ]
