# Generated by Django 3.2.4 on 2021-06-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210629_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietorder',
            old_name='is_finished',
            new_name='is_purchased',
        ),
    ]
