# Generated by Django 3.2.4 on 2021-06-22 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_dietorder_date_of_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietorder',
            name='date_of_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dietorder',
            name='date_of_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
