# Generated by Django 3.2.4 on 2021-07-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210706_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
