# Generated by Django 3.2.4 on 2021-07-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_ordercheckout_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaserInfo',
        ),
    ]
