# Generated by Django 3.2.4 on 2021-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_registrationprzelewy24'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprzelewy24',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registrationprzelewy24',
            name='client',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registrationprzelewy24',
            name='merchantID',
            field=models.IntegerField(default=11111),
        ),
        migrations.AddField(
            model_name='registrationprzelewy24',
            name='timeLimit',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='registrationprzelewy24',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
