# Generated by Django 3.2.4 on 2021-06-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_dietorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietorder',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dietorder',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
