# Generated by Django 3.2.4 on 2021-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_auto_20210615_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='to_pay',
            field=models.FloatField(null=True),
        ),
    ]
