# Generated by Django 3.2.4 on 2021-06-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
