# Generated by Django 3.2.4 on 2021-06-14 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='diet_images')),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DietOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megabytes', models.IntegerField()),
                ('days', models.IntegerField()),
                ('date_of_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.diet')),
                ('price_per_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diet_order_price', to='menu.diet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dish', models.TextField()),
                ('second_dish', models.TextField()),
                ('third_dish', models.TextField()),
                ('fourth_dish', models.TextField()),
                ('fifth_dish', models.TextField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.diet')),
            ],
        ),
    ]
