# Generated by Django 3.2.4 on 2021-06-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='calories',
        ),
    ]
