# Generated by Django 3.2.4 on 2021-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_delete_dietorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
