# Generated by Django 3.2.4 on 2021-06-07 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_diet_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='image',
            field=models.ImageField(upload_to='diet_images'),
        ),
        migrations.CreateModel(
            name='DietExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dish', models.TextField()),
                ('second_dish', models.TextField()),
                ('third_dish', models.TextField()),
                ('fourth_dish', models.TextField()),
                ('fifth_dish', models.TextField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.diet')),
            ],
        ),
    ]
