# Generated by Django 3.2.4 on 2021-06-10 13:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_diet_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='diet',
            name='image',
            field=models.ImageField(upload_to='diet_images'),
        ),
        migrations.CreateModel(
            name='DietOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megabites', models.IntegerField()),
                ('days', models.IntegerField()),
                ('date_of_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.diet')),
                ('price_per_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diet_order_price', to='menu.diet')),
            ],
        ),
        migrations.CreateModel(
            name='DietExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dish', models.TextField()),
                ('second_dish', models.TextField()),
                ('third_dish', models.TextField()),
                ('fourth_dish', models.TextField()),
                ('fifth_dish', models.TextField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.diet')),
            ],
        ),
    ]
